# GitHub Actions Test Automation Pipeline

Complete CI/CD workflow for automated testing.

```yaml
# .github/workflows/test-automation.yml
name: Test Automation Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info

    - name: Comment coverage on PR
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run database migrations
      run: npm run db:migrate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Run integration tests
      run: npm run test:integration
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        REDIS_URL: redis://localhost:6379

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Build application
      run: npm run build

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  performance-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run performance tests
      run: npm run test:performance

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance-results/

  security-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run security audit
      run: npm audit --production --audit-level moderate

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: javascript
```

## Pipeline Stages

### 1. Unit Tests
- Fast feedback on code changes
- Coverage reporting with thresholds
- Codecov integration for tracking
- PR comments with coverage diff

### 2. Integration Tests
- Runs with PostgreSQL and Redis services
- Database migrations before tests
- Isolated test database
- Service health checks

### 3. E2E Tests
- Full browser automation with Playwright
- Multi-browser testing (Chrome, Firefox, Safari)
- Screenshot/video capture on failure
- Test artifact retention

### 4. Performance Tests
- Only runs on main branch pushes
- Load testing critical endpoints
- Performance regression detection
- Results uploaded as artifacts

### 5. Security Tests
- npm audit for dependency vulnerabilities
- CodeQL static analysis
- Configurable severity levels

## Package Scripts

Add these to your `package.json`:

```json
{
  "scripts": {
    "test": "jest",
    "test:unit": "jest --testMatch='**/*.test.{js,ts}'",
    "test:integration": "jest --testMatch='**/*.integration.test.{js,ts}' --runInBand",
    "test:e2e": "playwright test",
    "test:performance": "node scripts/run-performance-tests.js",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage",
    "db:migrate": "node scripts/migrate.js",
    "db:migrate:test": "NODE_ENV=test node scripts/migrate.js",
    "db:seed:test": "NODE_ENV=test node scripts/seed.js"
  }
}
```

## Environment Variables

Set these in GitHub Actions secrets:

```yaml
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  API_KEY: ${{ secrets.API_KEY }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
```

## Conditional Execution

### Run on specific branches
```yaml
on:
  push:
    branches: [ main, develop, feature/* ]
```

### Run specific jobs conditionally
```yaml
performance-tests:
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
```

### Skip CI
Add to commit message: `[skip ci]` or `[ci skip]`

## Parallel vs Sequential

### Parallel Jobs
By default, jobs run in parallel for speed:
- unit-tests
- integration-tests
- e2e-tests

### Sequential Steps
Steps within a job run sequentially:
```yaml
- name: Install dependencies
  run: npm ci
- name: Run tests
  run: npm test
```

### Job Dependencies
Make jobs wait for others:
```yaml
deploy:
  needs: [unit-tests, integration-tests, e2e-tests]
  runs-on: ubuntu-latest
```

## Artifact Management

### Upload Test Results
```yaml
- name: Upload test results
  uses: actions/upload-artifact@v3
  if: always()
  with:
    name: test-results
    path: test-results/
    retention-days: 30
```

### Download Artifacts
```yaml
- name: Download test results
  uses: actions/download-artifact@v3
  with:
    name: test-results
```

## Notifications

### Slack Notification
```yaml
- name: Slack Notification
  uses: 8398a7/action-slack@v3
  if: failure()
  with:
    status: ${{ job.status }}
    webhook_url: ${{ secrets.SLACK_WEBHOOK }}
```

### Email Notification
Configure in repository settings → Notifications

## Best Practices

- Use `npm ci` instead of `npm install` for reproducible builds
- Cache dependencies to speed up workflows
- Set appropriate timeout limits
- Use health checks for service containers
- Upload artifacts on failure for debugging
- Keep secrets in GitHub Secrets, never in code
- Use matrix builds for multiple Node.js versions
- Run expensive tests (E2E, performance) only when needed
